export const plantList = [
    {
        name: 'Monstera',
        category: 'Classique',
        id: '1ed',
        isBestSale: true,
        cover: './images/monstera.jpg',
        light: 2,
        water: 3,
        price: 1500,
    },
    {
        name: 'Ficus lyrata',
        category: 'Classique',
        cover: './images/fucus-lyrata.jpeg',
        id: '2ab',
        light: 3,
        water: 1,
        price: 2000,
    },
    {
        name: 'Pothos argenté',
        category: 'Classique',
        id: '3sd',
        light: 1,
        cover: './images/pothos-argente.jpg',
        water: 2,
        price: 1000,
    },
    {
        name: 'Yucca',
        category: 'Classique',
        id: '4kk',
        light: 3,
        cover: './images/yucca.jpeg',
        water: 1,
        price: 3000,
    },
    {
        name: 'Olivier',
        category: 'Extérieur',
        id: '5pl',
        light: 3,
        cover: './images/olivier.jpeg',
        water: 1,
        price: 2500,
    },
    {
        name: 'Géranium',
        category: 'Extérieur',
        id: '6uo',
        light: 2,
        cover: './images/geranium.jpg',
        water: 2,
        price: 5000,
    },
    {
        name: 'Basilique',
        category: 'Extérieur',
        id: '7ie',
        isBestSale: true,
        light: 2,
        cover: './images/basilique.jpg',
        water: 3,
        price: 750,
    },
    {
        name: 'Aloe',
        category: 'Plante grasse',
        id: '8fp',
        light: 2,
        cover: './images/aloe.jpg',
        water: 1,
        price: 1850,
    },
    {
        name: 'Succulente',
        category: 'Plante grasse',
        id: '9vn',
        light: 2,
        cover: './images/succulente.webp',
        water: 1,
        price: 2200,
    },
]
