export const plantList = [
    {
        name: 'Monstera',
        category: 'Classique',
        id: '1ed',
        isBestSale: true,
        cover: 'monstera.jpg',
        light: 2,
        water: 3,
    },
    {
        name: 'Ficus lyrata',
        category: 'Classique',
        id: '2ab',
        light: 3,
        water: 1,
    },
    {
        name: 'Pothos argenté',
        category: 'Classique',
        id: '3sd',
        light: 1,
        water: 2,
    },
    {
        name: 'Yucca',
        category: 'Classique',
        id: '4kk',
        light: 3,
        water: 1,
    },
    {
        name: 'Olivier',
        category: 'Extérieur',
        id: '5pl',
        light: 3,
        water: 1,
    },
    {
        name: 'Géranium',
        category: 'Extérieur',
        id: '6uo',
        light: 2,
        water: 2,
    },
    {
        name: 'Basilique',
        category: 'Extérieur',
        id: '7ie',
        isBestSale: true,
        light: 2,
        water: 3,
    },
    {
        name: 'Aloe',
        category: 'Plante grasse',
        id: '8fp',
        light: 2,
        water: 1,
    },
    {
        name: 'Succulente',
        category: 'Plante grasse',
        id: '9vn',
        light: 2,
        water: 1,
    },
]
